#!/bin/dash

# Check if .shrug exists
if [ -d ".shrug" ]
then
    echo "$0: error: .shrug already exists" >> /dev/stderr
    exit
fi


mkdir .shrug
mkdir .shrug/index
echo "Initialized empty shrug repository in .shrug"