#!/bin/dash

# Check if .shrug exists
if [ ! -d ".shrug" ]
then
    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
    exit 1;
elif [ $# -eq 0 ]
then
    echo "usage: shrug-add <filenames>"
    exit
fi

while [ $1 ]
do      #Start with not [-./] follow by more than 1 char : Optional : (.)
    if echo $1 | egrep "^[^-./][A-Za-z0-9]*(.[A-Za-z0-9]+)*" > /dev/null # Valid Filename
    then
        if [ -f $1 ]                                            # File Exists in working directory
        then
            if [ ! -d ".shrug/index" ]
            then
                mkdir ".shrug/index"
            fi
            cp $1 ".shrug/index/"
        elif [ -f ".shrug/index/$1" ]                           # File exist in index but not in working directory
        then
            rm ".shrug/index/$1"
        else                                                    # File not Exists
            echo "$0: error: can not open '$1'" >> /dev/stderr
            exit 1
        fi
    elif echo $1 | egrep "^(-)+[A-Za-z]*" > /dev/null           # Flag Specified
    then
        echo "usage: shrug-add <filenames>"
        exit
    else
        echo "$0: error: invalid filename '$1'" >> /dev/stderr  # Other Cases (Invalid filename)
        exit 1
    fi
    shift
done


# TODO: Unhandled cases
# --
