#!/bin/dash

IFS="
"

# Constants
usage="usage: shrug-commit [-a] -m commit-message"

# Check if .shrug exists
if [ ! -d ".shrug" ]
then
    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
    exit 1;
fi

# Check argument number
if [ $# -lt 2 ]
then
    echo $usage
    exit 1
# Process Arguments
else
    while [ $1 ]
    do 
        if echo $1 | egrep "^-m$" > /dev/null && echo $2 | egrep -v "^-.+" > /dev/null
        then
            msg=$2
            shift
        elif echo $1 | egrep "^-a$" > /dev/null
        then
            for file in `find .shrug/index -type f`
            do
                filename=`basename $file`
                `shrug-add $filename`
            done
        else
            echo $usage
            exit 1
        fi
        shift
    done
fi

# Check if repo has previous commit
commit_no=0
if [ ! -f .shrug/commit_no ]
then
    mkdir .shrug/commit
    echo $commit_no > .shrug/commit_no
else
    commit_no=`cat .shrug/commit_no`
    commit_no=$(($commit_no+1))
fi

last_commit_no="`find .shrug/commit -mindepth 1 -type d -exec basename {} \; | sort | tail -1`"
# Not initial commit
if [ ! $last_commit_no = "" ]
then           
    differ=`shrug-cmp ".shrug/index" ".shrug/commit/$last_commit_no" `
    if [ -n "$differ" ]
    then
        for line in $differ
        do
            file=` echo $line | cut -d " " -f2 `
        done
        cp -r ".shrug/index/." ".shrug/commit/$commit_no"
        echo "$commit_no $msg" >> ".shrug/log"
        echo "$commit_no" > .shrug/commit_no
        echo "Committed as commit $commit_no"
    else
        echo "nothing to commit"
    fi
# Initial commit
else                            
    cp -r ".shrug/index/." ".shrug/commit/$commit_no"
    echo "$commit_no $msg" >> ".shrug/log"
    echo "$commit_no" > .shrug/commit_no
    echo "Committed as commit $commit_no"
fi
