#!/bin/dash

# Check if .shrug exists
if [ ! -d ".shrug" ]
then
    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
    exit 1;
elif [ $# -eq 0 ]
then
    echo "usage: shrug-add <filenames>"
    exit
fi

while [ $1 ]
do
    # Valid Filename
    if echo $1 | egrep "^[^-./][A-Za-z0-9]*(.[A-Za-z0-9]+)*" > /dev/null 
    then
        # File Exists in working directory
        if [ -f $1 ]                                            
        then
            if [ ! -d ".shrug/index" ]
            then
                mkdir ".shrug/index"
            fi
            cp $1 ".shrug/index/"
        # File exist in index but not in working directory
        elif [ -f ".shrug/index/$1" ]                           
        then
            rm ".shrug/index/$1"
        # File not Exists
        else                                                    
            echo "$0: error: can not open '$1'" >> /dev/stderr
            exit 1
        fi
    # Flag Specified
    elif echo $1 | egrep "^(-)+[A-Za-z]*" > /dev/null           
    then
        echo "usage: shrug-add <filenames>"
        exit
    # Other Cases (Invalid filename)
    else
        echo "$0: error: invalid filename '$1'" >> /dev/stderr  
        exit 1
    fi
    shift
done