#!/bin/dash

IFS=" "

usage="usage: shrug-rm [--force] [--cached] <filenames>"
index_dir=".shrug/index"
force_flag=0
cached_flag=0
commit_dir=".shrug/commit"


commit_no=-1
if [ -d $commit_dir ]
then
    commit_no=`cat $log_file | tail -1 | cut -d " " -f1`
fi


# Check if .shrug exists
if [ ! -d ".shrug" ]
then
    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
    exit 1;
fi

files=""

# Check argument number
if [ $# -lt 1 ]
then
    echo "$usage"
    exit 
# Process Flags
else
    for argv in $@
    do
        if echo $argv | egrep "^--force$" > /dev/null
        then
            force_flag=1
        elif echo $argv | egrep "^--cached$" > /dev/null
        then
            cached_flag=1
        elif echo $argv | egrep "^-" > /dev/null
        then
            echo "$usage"
            exit
        elif [ -n "$files" ]
        then
            files=` echo "$files $argv" `
        else 
            files="$argv"
        fi
    done
fi

if [ -z "$files" ]
then
    echo "$usage"
    exit
fi

for file in $files
do
    # check if file exists in index
    if [ -f "$index_dir/$file" ]
    then
        # Check if file inside index is different from file in directory
        differ=` diff $file $index_dir/$file `
        if [ -n "$differ" ] && [ $force_flag -ne 1 ]
        then
            echo "$0: error: '$file' in repository is different to working file" >> /dev/stderr
            exit 1
        elif [ $commit_no -ne -1 ] && [ -n `diff $index_dir/$file $commit_dir/$commit_no/$file` ] && [ $cached_flag -ne 1 ]
        then
            echo "$0: error: '$file' has changes staged in the index" >> /dev/stderr
            exit 1
        fi

        rm "$index_dir/$file"

        # Remove file on current directory if --cached is not specified
        if [ $cached_flag -ne 1 ]
        then
            rm "$file"
        fi
    else
        echo "$0: error: '$file' is not in the shrug repository" >> /dev/stderr
        exit 1;
    fi
done