#!/bin/dash
# if different exit 0
# same exit 1

if [ ! -f $1 ] || [ ! -f $2 ]
then
    echo "exit 0"
    exit 0
fi

if `diff $1 $2` 2>/dev/null
then
    echo "exit 1"
    exit 1
fi
echo "exit 0"
exit 0