#!/bin/dash


# Check if .shrug exists
if [ ! -d ".shrug" ]
then
    echo "$0: error: no .shrug directory containing shrug repository exists" \
        >> /dev/stderr
    exit 1;
elif [ ! -f ".shrug/log" ]
then
    echo "$0: error: your repository does not have any commits yet" \
        >> /dev/stderr
    exit 1;
elif [ $# -ne 0 ]
then 
    echo "usage: shrug-log" >> /dev/stderr
    exit 1;
else
    cat .shrug/log | sort -rn
fi