#!/bin/dash


usage="usage: shrug-branch [-d] <branch>"

# Not a shrug repository
if [ ! -d ".shrug" ]
then
    echo "$0: error: no .shrug directory containing shrug repository exists" >>/dev/stderr
    exit 1
# No Arguments
elif [ $# -gt 2 ]
then
    echo "$usage"
    exit 1
# No commit
elif [ ! -f .shrug/log ]
then
    echo "$0: error: your repository does not have any commits yet" >>/dev/stderr
    exit 1
fi


branch=""
delete_flag=0
for argv in $@
do
    # Detect -d flag
    if echo $argv | egrep "^(-d)$" -q
    then
        delete_flag=1
    # Detect invalid flag
    elif echo $argv | egrep "^-" -q && echo $argv | egrep "^--.+" -q
    then
        echo "$usage"
        exit 1
    # Treat -- as nothing
    elif echo $argv | egrep "^--$" -q
    then
        continue
    else
        # Check for invalid branch name
        if echo $argv | egrep -v "^[-_A-Za-z0-9]*$" -q \
            || echo $argv | egrep -v "[-_A-Za-z]" -q
        then
            echo "$0: error: invalid branch name '$argv'" >>/dev/stderr
            exit 1
        # Valid branch name
        else
            branch=$argv
        fi
    fi
done

# Branch not specified
if [ -z $branch ]
then
    # Delete flag specified
    if [ $delete_flag -eq 1 ]
    then
        echo "$0: error: branch name required"
        exit 1
    # List all branch
    else
        # No branch created yet
        if [ ! -d .shrug/branch ]
        then
            echo "master"
        else
            branches="`find .shrug/branch -mindepth 1 -maxdepth 1 -type d | sort `"
            for branch in $branches
            do
                branch=`basename $branch`
                echo "$branch"
            done
        fi
        exit 0
    fi
# Branch specified
else
    # Delete flag specified
    if [ $delete_flag -eq 1 ]
    then
        # Branch not exist
        if [ ! -d .shrug/branch/$branch ]
        then
            echo "$0: error: branch '$branch' does not exist" >>/dev/stderr
            exit 1
        # Branch exists
        else
            if [ $branch = "master" ]
            then
                echo "shrug-branch: error: can not delete branch 'master'"
                exit 1
            fi
            rm -rf ".shrug/branch/$branch" &&
            echo "Deleted branch '$branch'"
        fi
    # Create branch
    else
        if [ ! -d .shrug/branch ]
        then
            mkdir .shrug/branch
            mkdir .shrug/branch/master
        fi

        # check if branch with given name exist
        if [ -d .shrug/branch/$branch ]
        then
            echo "$0: error: branch '$branch' already exists"
            exit 1
        fi

        mkdir ".shrug/branch/$branch"
        mkdir ".shrug/branch/$branch/commit"
        
        cp -r .shrug/commit .shrug/branch/$branch
        cp .shrug/log .shrug/branch/$branch
    fi
fi