#!/bin/dash

# Check if .shrug exists
if [ $# -ne 0 ]
then
    echo "usage: shrug-init"
    exit 1
elif [ -d ".shrug" ]
then
    echo "$0: error: .shrug already exists" >> /dev/stderr
    exit 1
fi


mkdir .shrug
mkdir .shrug/index
echo "master" > .shrug/current_branch
echo "Initialized empty shrug repository in .shrug"
