#!/bin/dash
# if different exit 0
# same exit 1

if [ ! -f $1 ] || [ ! -f $2 ]
then
    exit 0
fi

if [ "`sha256sum $1 | cut -d ' ' -f1`" = "`sha256sum $2 | cut -d ' ' -f1`" ] 
then
    exit 1
fi
exit 0
